# Generated by Django 4.0.3 on 2022-03-18 15:37

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Автори на песни',
                'ordering': ('author_name',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100, verbose_name='Жарн')),
            ],
            options={
                'verbose_name': 'Жарн',
                'verbose_name_plural': 'Жарнове на Песни',
                'ordering': ('genre_name',),
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(max_length=100, verbose_name='Изпълнител')),
            ],
            options={
                'verbose_name': 'Изпълнител',
                'verbose_name_plural': 'Изпълнители',
                'ordering': ('singer_name',),
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=200, verbose_name='Заглавие')),
                ('song_text', tinymce.models.HTMLField(verbose_name='Текст на Песен')),
                ('song_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pesni4ki.author', verbose_name='Автор ')),
                ('song_gernes', models.ManyToManyField(to='pesni4ki.genre', verbose_name='Жарн')),
                ('song_singer', models.ManyToManyField(to='pesni4ki.singer', verbose_name='Изпълнител')),
            ],
            options={
                'verbose_name': 'Песен',
                'verbose_name_plural': 'Песни',
                'ordering': ('song_title',),
            },
        ),
    ]
